"use client";
import { useState, useEffect, useMemo, useRef } from "react";
import { useBackendMarkaStore } from "@/stores/backendMarkaStore";
import { useBackendToyStore } from "@/stores/backendToyStore";
import { Card, CardContent } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Input } from "@/components/ui/Input";
import { Label } from "@/components/ui/Label";
import { useToast } from "@/components/ui/Toast";
import { cn } from "@/lib/utils";
import { formatWeight, safeNumber } from "@/lib/utils/number";
import { printToyLabelVerbose } from "@/lib/utils/print";
import {
  Tag,
  ChevronDown,
  Search,
  Scale,
  Zap,
  Plus,
  Printer,
  AlertCircle,
  Lock,
  Unlock,
  RefreshCw,
  Target,
  Loader2
} from "lucide-react";
import { Marka } from "@/types/marka";

interface ToyFormProps {
  currentWeight: number;
  isStable: boolean;
  isConnected: boolean;
  isSerialConnected?: boolean;
  hardwareConnectedCount: number;
  activeMarkas: Marka[];
  className?: string;
  onMarkaChange?: (markaId: string) => void;
}

export function ToyForm({
  currentWeight,
  isStable,
  isConnected,
  isSerialConnected,
  hardwareConnectedCount,
  activeMarkas,
  className,
  onMarkaChange
}: ToyFormProps) {
  const { createToy, getNextOrderNo } = useBackendToyStore();
  const { toast } = useToast();

  const [selectedMarkaId, setSelectedMarkaId] = useState("");
  const [selectedBrigade, setSelectedBrigade] = useState("1-Brigada");
  const [brutto, setBrutto] = useState<number | "">("");
  const [tara, setTara] = useState<number | "">("");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isTaraLocked, setIsTaraLocked] = useState(true);
  const [showMarkaDropdown, setShowMarkaDropdown] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [error, setError] = useState<string | null>(null);

  const dropdownRef = useRef<HTMLDivElement>(null);

  // Determine if any scale (network or local serial) is active
  const isScaleActive = (isConnected && hardwareConnectedCount > 0) || !!isSerialConnected;

  useEffect(() => {
    // If a scale is active, automatically sync Brutto with scale reading
    if (isScaleActive) {
      setBrutto(currentWeight);
    }
  }, [currentWeight, isScaleActive]);

  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setShowMarkaDropdown(false);
      }
    }
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  const selectedMarka = useMemo(() =>
    activeMarkas.find(m => m.id === selectedMarkaId),
    [activeMarkas, selectedMarkaId]
  );

  const filteredMarkas = useMemo(() =>
    activeMarkas.filter(m =>
      m.number.toString().includes(searchQuery) ||
      m.productType.toLowerCase().includes(searchQuery.toLowerCase()) ||
      m.ptm?.toLowerCase().includes(searchQuery.toLowerCase())
    ),
    [activeMarkas, searchQuery]
  );

  const netto = useMemo(() => {
    const b = Number(brutto) || 0;
    const t = Number(tara) || 0;
    const res = b - t;
    return res > 0 ? res : 0;
  }, [brutto, tara]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedMarkaId) {
      setError("Markani tanlang");
      return;
    }
    if (netto <= 0) {
      setError("Vazn 0 dan ko'p bo'lsin");
      return;
    }
    if (isConnected && hardwareConnectedCount > 0 && !isStable) {
      setError("Vazn turg'un emas, biroz kuting");
      return;
    }

    setIsSubmitting(true);
    setError(null);

    try {
      // const orderNo = await getNextOrderNo(selectedMarkaId); // Deprecated: Let backend handle orderNo
      const newToy = await createToy({
        markaId: selectedMarkaId,
        // orderNo is auto-generated by backend
        brutto: Number(brutto),
        tara: Number(tara),
        netto: netto,
        brigade: selectedBrigade,
        productType: (selectedMarka?.productType as any) || 'TOLA'
      });

      // Robust extraction of toy data from backend response
      const toy = (newToy as any).item || (newToy as any).data || (newToy as any).toy || newToy;
      const tOrderNo = toy.orderNo || (toy as any).order_no || (newToy as any).orderNo || (newToy as any).order_no || 0;
      const tId = toy.id || (newToy as any).id || '';

      toast.success(`Toy #${tOrderNo} saqlandi`);
      setBrutto("");

      await printToyLabelVerbose({
        id: tId,
        orderNo: tOrderNo.toString(),
        markaNumber: selectedMarka?.number.toString() || '???',
        productType: toy.productType || (toy as any).product_type || (newToy as any).productType || 'TOLA',
        netto: safeNumber(toy.netto) || safeNumber((toy as any).netto_weight) || safeNumber((newToy as any).netto) || 0,
        brutto: safeNumber(toy.brutto) || safeNumber((toy as any).brutto_weight) || safeNumber((newToy as any).brutto) || 0,
        tara: safeNumber(toy.tara) || safeNumber((toy as any).tara_weight) || safeNumber((newToy as any).tara) || 0,
        createdAt: toy.createdAt || (toy as any).created_at || new Date().toISOString(),
        ptm: selectedMarka?.ptm,
        selection: selectedMarka?.selection,
        pickingType: selectedMarka?.pickingType,
        sex: selectedMarka?.sex,
        brigade: selectedBrigade
      }, { method: 'browser' });
    } catch (err: any) {
      setError(err.message || "Xato");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Card className={cn("bg-white/80 dark:bg-slate-900/60 backdrop-blur-lg border border-white/50 dark:border-white/10 rounded-[2.5rem] shadow-xl shadow-black/5 flex flex-col h-full animate-in fade-in slide-in-from-bottom-4 duration-500", className)}>
      <div className="p-3 lg:p-4 border-b border-white/40 dark:border-white/5 bg-white/20 dark:bg-black/20 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-7 h-7 rounded-lg bg-primary/10 dark:bg-white/5 text-primary flex items-center justify-center">
            <Plus size={16} strokeWidth={2.5} />
          </div>
          <div>
            <h2 className="text-[11px] font-black text-slate-900 dark:text-white uppercase tracking-tight leading-none">Registratsiya</h2>
            <p className="text-[8px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mt-0.5">Yangi Toy</p>
          </div>
        </div>
        <Target size={16} strokeWidth={2} className="text-primary/20" />
      </div>

      <CardContent className="p-3 lg:p-4 flex-1 overflow-y-auto scrollbar-none">
        <form onSubmit={handleSubmit} className="space-y-3">

          {/* Marka Selection Hub */}
          <div className="space-y-2" ref={dropdownRef}>
            <div className="flex items-center justify-between px-1">
              <Label className="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest leading-none">Marka Identifikatori</Label>
              {selectedMarka && (
                <span className="text-[8px] font-bold text-primary bg-primary/5 px-1.5 py-0.5 rounded-md uppercase tracking-widest animate-in slide-in-from-right-2">TANLANDI</span>
              )}
            </div>
            <div className="relative">
              <button
                type="button"
                onClick={() => setShowMarkaDropdown(!showMarkaDropdown)}
                className={cn(
                  "w-full h-11 px-4 flex items-center justify-between rounded-xl border border-white/60 dark:border-white/10 transition-all active:scale-[0.98]",
                  showMarkaDropdown ? "bg-white dark:bg-slate-800 border-primary shadow-lg ring-4 ring-primary/5" : "bg-slate-50/50 dark:bg-white/5 border-transparent hover:bg-slate-50 dark:hover:bg-white/10 hover:border-border"
                )}
              >
                <div className="flex items-center gap-3">
                  <div className={cn("w-7 h-7 rounded-lg flex items-center justify-center transition-all", selectedMarka ? "bg-primary text-white shadow-md shadow-primary/20" : "bg-white dark:bg-white/5 text-slate-300 dark:text-slate-600 shadow-sm")}>
                    <Tag size={14} strokeWidth={2} />
                  </div>
                  <span className={cn("text-[11px] font-bold uppercase tracking-tight truncate max-w-[180px]", selectedMarka ? "text-slate-900 dark:text-white" : "text-slate-400 dark:text-slate-500")}>
                    {selectedMarka ? `#${selectedMarka.number} — ${selectedMarka.productType}` : "Markani Tanlang..."}
                  </span>
                </div>
                <ChevronDown size={16} strokeWidth={2} className={cn("text-slate-400 transition-transform duration-500", showMarkaDropdown && "rotate-180")} />
              </button>

              {showMarkaDropdown && (
                <div className="absolute z-50 w-full mt-2 bg-white/95 dark:bg-slate-900/95 backdrop-blur-xl border border-border dark:border-white/10 rounded-2xl shadow-2xl p-3 animate-in fade-in zoom-in-95 duration-200">
                  <div className="relative mb-3">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-slate-400" strokeWidth={2} />
                    <Input
                      placeholder="Qidiruv..."
                      value={searchQuery}
                      onChange={(e) => setSearchQuery(e.target.value)}
                      className="pl-9 py-2 px-3 h-9 bg-slate-50 dark:bg-white/5 border-border dark:border-white/10 rounded-lg text-[10px] font-bold text-slate-900 dark:text-white focus:ring-primary/20 transition-all font-mono"
                    />
                  </div>
                  <div className="max-h-40 overflow-y-auto scrollbar-none space-y-1 p-0.5">
                    {filteredMarkas.length > 0 ? filteredMarkas.map((marka) => (
                      <button
                        key={marka.id}
                        type="button"
                        onClick={() => {
                          setSelectedMarkaId(marka.id);
                          onMarkaChange?.(marka.id);
                          setShowMarkaDropdown(false);
                          setSearchQuery("");
                        }}
                        className={cn(
                          "w-full p-2.5 flex items-center justify-between rounded-lg transition-all border",
                          selectedMarkaId === marka.id
                            ? "bg-primary text-white border-primary shadow-lg shadow-primary/20"
                            : "bg-white dark:bg-white/5 border-transparent text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-white/10 hover:border-border dark:hover:border-white/10"
                        )}
                      >
                        <div className="flex items-center gap-3">
                          <span className="text-xs font-bold font-mono">#{marka.number}</span>
                          <span className={cn("text-[8px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded-md", selectedMarkaId === marka.id ? "bg-white/20" : "bg-slate-100 dark:bg-white/10")}>
                            {marka.productType}
                          </span>
                        </div>
                        <span className="text-[9px] font-bold opacity-40 font-mono italic">{marka.used}/{marka.capacity}</span>
                      </button>
                    )) : (
                      <div className="py-6 text-center opacity-40">
                        <p className="text-[9px] font-bold uppercase tracking-widest">Marka yo'q</p>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* Brigade Selection - NEW */}
          <div className="space-y-2">
            <Label className="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Mas&apos;ul Brigada</Label>
            <div className="grid grid-cols-3 gap-2">
              {["1", "2", "3"].map((b) => (
                <button
                  key={b}
                  type="button"
                  onClick={() => setSelectedBrigade(`${b}-Brigada`)}
                  className={cn(
                    "h-10 rounded-xl text-[10px] font-black transition-all border",
                    selectedBrigade === `${b}-Brigada`
                      ? "bg-primary text-white border-primary shadow-lg shadow-primary/20"
                      : "bg-slate-50/50 dark:bg-white/5 border-transparent text-slate-400 dark:text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10"
                  )}
                >
                  {b}-B
                </button>
              ))}
            </div>
          </div>

          {/* Mass Parameter Matrix */}
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-1">Brutto</Label>
              <div className="relative group">
                <div className="absolute left-3 top-1/2 -translate-y-1/2 text-primary/40">
                  <Scale size={14} strokeWidth={2} />
                </div>
                <Input
                  type="number"
                  value={brutto}
                  readOnly={isScaleActive}
                  onChange={(e) => setBrutto(e.target.value ? Number(e.target.value) : "")}
                  className={cn(
                    "h-11 pl-9 pr-3 bg-slate-50/50 dark:bg-white/5 border-none rounded-xl font-mono text-sm font-bold text-slate-900 dark:text-white focus:ring-primary/20 transition-all",
                    isScaleActive && "text-primary dark:text-emerald-400 cursor-not-allowed opacity-80"
                  )}
                  placeholder="0.00"
                />
              </div>
            </div>

            <div className="space-y-2">
              <div className="flex items-center justify-between px-1">
                <Label className="text-[9px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">Tara</Label>
                <button
                  type="button"
                  onClick={() => setIsTaraLocked(!isTaraLocked)}
                  className={cn("w-6 h-6 rounded-lg flex items-center justify-center transition-all", isTaraLocked ? "text-slate-300 dark:text-slate-600" : "bg-primary/10 text-primary shadow-sm")}
                >
                  {isTaraLocked ? <Lock size={12} strokeWidth={2} /> : <Unlock size={12} strokeWidth={2} />}
                </button>
              </div>
              <div className="relative group">
                <div className="absolute left-3 top-1/2 -translate-y-1/2 text-primary/40">
                  <Zap size={14} strokeWidth={2} />
                </div>
                <Input
                  type="number"
                  value={tara}
                  readOnly={isTaraLocked}
                  onChange={(e) => setTara(e.target.value ? Number(e.target.value) : "")}
                  className={cn(
                    "h-11 pl-9 pr-3 bg-slate-50/50 dark:bg-white/5 border-none rounded-xl font-mono text-sm font-bold text-slate-900 dark:text-white focus:ring-primary/20 transition-all",
                    isTaraLocked && "text-slate-400 dark:text-slate-500 cursor-not-allowed opacity-60"
                  )}
                  placeholder="0.00"
                />
              </div>
            </div>
          </div>

          {/* Results Engine */}
          <div className="flex gap-4">
            {/* Primary Weight Displayer (Brutto) */}
            <div className="flex-1 min-h-[140px] flex flex-col items-center justify-center bg-primary/5 dark:bg-primary/10 rounded-2xl border border-primary/10 p-6 relative overflow-hidden group">
              <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
                <Scale size={80} />
              </div>

              <p className="text-[10px] font-black text-primary/60 dark:text-primary/40 uppercase tracking-[0.3em] mb-3">UMUMIY (BRUTTO)</p>

              <div className="flex flex-col items-center relative z-10 transition-transform duration-500 group-hover:scale-105">
                <div className="flex items-baseline gap-2">
                  <span className={cn(
                    "text-5xl font-black tabular-nums tracking-tighter transition-all duration-700 font-mono",
                    brutto > 0 ? "text-slate-900 dark:text-white" : "text-slate-200 dark:text-white/10"
                  )}>
                    {formatWeight(brutto, 'kg', 2)}
                  </span>
                  <span className="text-sm font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">kg</span>
                </div>
              </div>

              <div className="absolute bottom-0 left-0 w-full h-1 bg-primary/10">
                <div
                  className="h-full bg-primary transition-all duration-300"
                  style={{ width: `${Math.min((brutto / 230) * 100, 100)}%` }}
                />
              </div>
            </div>

            {/* Secondary Weights Matrix */}
            <div className="flex flex-col gap-3 w-40">
              <div className="flex-1 flex flex-col items-center justify-center bg-slate-50/50 dark:bg-white/5 rounded-2xl border border-slate-100 dark:border-white/10 p-4">
                <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest mb-1.5">SOF OG'IRLIGI (NETTO)</p>
                <div className="flex items-baseline gap-1">
                  <span className="text-xl font-bold dark:text-white font-mono">{formatWeight(Number(netto) || 0, 'kg', 2)}</span>
                  <span className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">kg</span>
                </div>
              </div>
              <div className="flex-1 flex flex-col items-center justify-center bg-slate-50/50 dark:bg-white/5 rounded-2xl border border-slate-100 dark:border-white/10 p-4">
                <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest mb-1.5">TARA</p>
                <div className="flex items-baseline gap-1">
                  <span className="text-xl font-bold dark:text-white font-mono">{formatWeight(Number(tara) || 0, 'kg', 2)}</span>
                  <span className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">kg</span>
                </div>
              </div>
            </div>
          </div>
          {/* Feedback & Submission Console */}
          <div className="space-y-3 pt-2">
            {error && (
              <div className="flex items-center gap-2 p-2.5 bg-destructive/5 border border-destructive/10 rounded-xl text-destructive animate-in slide-in-from-bottom-2 duration-300">
                <AlertCircle size={14} strokeWidth={2} />
                <p className="text-[9px] font-bold uppercase tracking-widest leading-none shrink-0">{error}</p>
              </div>
            )}

            <Button
              type="submit"
              disabled={isSubmitting || !selectedMarkaId || netto <= 0 || (isConnected && hardwareConnectedCount > 0 && !isStable)}
              className={cn(
                "w-full h-12 rounded-xl font-bold uppercase tracking-[0.2em] text-[10px] shadow-lg transition-all active:scale-[0.98] flex items-center justify-center gap-2.5",
                isConnected && hardwareConnectedCount > 0 && !isStable
                  ? "bg-slate-200 dark:bg-white/5 text-slate-400 dark:text-slate-500 cursor-not-allowed"
                  : "bg-primary text-white hover:bg-green-700 shadow-primary/20 dark:hover:bg-green-600"
              )}
            >
              {isSubmitting ? (
                <>
                  <RefreshCw className="h-3.5 w-3.5 animate-spin" strokeWidth={2} />
                  <span>Saqlanmoqda...</span>
                </>
              ) : isConnected && hardwareConnectedCount > 0 && !isStable ? (
                <>
                  <Loader2 className="h-3.5 w-3.5 animate-spin" strokeWidth={2} />
                  <span>Kuting...</span>
                </>
              ) : (
                <>
                  <Printer className="h-3.5 w-3.5" strokeWidth={2} />
                  <span>Chop etish va muhrlash</span>
                </>
              )}
            </Button>
          </div>
        </form>
      </CardContent >
    </Card >
  );
}